name: SwiftLint

on:
  pull_request:
    branches:
      - '**' # Run on all branches for PRs

jobs:
  lint:
    runs-on: ubuntu-latest # Use the latest Linux environment

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install SwiftLint
      - name: Install SwiftLint
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git libssl-dev libcurl4-openssl-dev libz-dev
          curl -fsSL https://swift.org/builds/swift-5.9.1-release/ubuntu2004/swift-5.9.1-RELEASE/swift-5.9.1-RELEASE-ubuntu20.04.tar.gz | tar -xz -C /usr/local --strip-components=1
          git clone https://github.com/realm/SwiftLint.git
          cd SwiftLint
          swift build -c release
          sudo cp .build/release/swiftlint /usr/local/bin

      # Step 3: Run SwiftLint and parse errors
      - name: Run SwiftLint
        run: |
          set -o pipefail
          swiftlint lint --strict --quiet | sed -E 's/^(.*):([0-9]+):([0-9]+): (warning|error|[^:]+): (.*)/::\4 title=Lint error,file=\1,line=\2,col=\3::\5\n\1:\2:\3/'
