name: SwiftLint

on:
  push:
    branches:
      - '**' # Run on all branches
  pull_request:
    branches:
      - '**' # Run on all branches for PRs

jobs:
  lint:
    runs-on: ubuntu-latest # Use the latest Linux environment

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Run SwiftLint and parse errors
      - name: Lint
        run: |
          set -o pipefail
          swiftlint lint --strict --quiet | sed -E 's/^(.*):([0-9]+):([0-9]+): (warning|error|[^:]+): (.*)/::\4 title=Lint error,file=\1,line=\2,col=\3::\5\n\1:\2:\3/'
